# Generated by Django 3.1.12 on 2025-03-23 09:34

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rahatsizlik',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('isim', models.CharField(max_length=100, unique=True)),
                ('aciklama', models.TextField(blank=True)),
                ('belirtiler', models.TextField(blank=True, help_text='Rahatsızlığın belirtilerini yazın')),
                ('risk_faktorleri', models.TextField(blank=True, help_text='Risk faktörlerini yazın')),
                ('onlemler', models.TextField(blank=True, help_text='Alınması gereken önlemleri yazın')),
                ('olusturulma_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('etiketler', models.TextField(blank=True)),
                ('seviye', models.CharField(choices=[('hafif', 'Hafif'), ('orta', 'Orta'), ('ciddi', 'Ciddi'), ('kronik', 'Kronik'), ('akut', 'Akut')], max_length=50)),
                ('yayginlik', models.CharField(choices=[('nadir', 'Nadir'), ('az', 'Az'), ('orta', 'Orta'), ('yaygin', 'Yaygın'), ('cok_yaygin', 'Çok Yaygın')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bitki',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('isim', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('tek_yillik', 'Tek Yıllık'), ('cok_yillik', 'Çok Yıllık'), ('agac', 'Ağaç'), ('cicek', 'Çiçek'), ('sarmaşık', 'Sarmaşık'), ('sukulent', 'Sukulent'), ('kaktus', 'Kaktüs'), ('ot', 'Ot'), ('cim', 'Çim'), ('yosun', 'Yosun'), ('mantar', 'Mantar'), ('diger', 'Diğer')], max_length=50)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='bitkiler/')),
                ('faydalar', models.TextField()),
                ('kullanim', models.TextField()),
                ('hazirlama', models.TextField()),
                ('uyarilar', models.TextField(blank=True)),
                ('doz', models.TextField(blank=True)),
                ('olusturulma_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('etiketler', models.TextField(blank=True)),
                ('mevsim', models.TextField(blank=True)),
                ('yan_etkiler', models.TextField(blank=True, help_text='Yan etkileri virgülle ayırarak yazın')),
                ('kontrendikasyonlar', models.TextField(blank=True, help_text='Kontrendikasyonları virgülle ayırarak yazın')),
                ('saklama_kosullari', models.TextField(blank=True)),
                ('raf_omru', models.CharField(blank=True, max_length=50)),
                ('kaynak', models.CharField(blank=True, max_length=200)),
                ('bilimsel_ad', models.CharField(blank=True, max_length=100)),
                ('aile', models.CharField(blank=True, max_length=100)),
                ('cins', models.CharField(blank=True, max_length=100)),
                ('tur', models.CharField(blank=True, max_length=100)),
                ('rahatsizliklar', models.ManyToManyField(related_name='bitkiler', to='sifalibitkiler.Rahatsizlik')),
            ],
        ),
    ]
